from __future__ import annotations

from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[3]
DEFAULT_PROMPT_PATH = REPO_ROOT / "prompts/runtime/normalization/recipe-normalization-v1.md"
DEFAULT_SCHEMA_PATH = REPO_ROOT / "prompts/schemas/recipe-normalization-output.schema.json"
DEFAULT_PREPROCESSING_PROMPT_PATH = REPO_ROOT / "prompts/runtime/translation/recipe-translation-v1.md"
DEFAULT_PREPROCESSING_SCHEMA_PATH = REPO_ROOT / "prompts/schemas/recipe-translation-output.schema.json"
DEFAULT_REPORT_DIR = REPO_ROOT / "data/reports"
SWEDISH_RECIPE_UNITS_PATH = REPO_ROOT / "data/reference/swedish_recipe_units.json"
SWEDISH_RECIPE_TERMS_PATH = REPO_ROOT / "data/reference/swedish_recipe_terms.json"

SCHEMA_VERSION = "1.0.0"
ARTIFACT_TYPE = "intake_candidate_bundle"
REPORT_TYPE = "recipe_normalization_run"

DISH_ROLES = [
    "Breakfast",
    "Brunch",
    "Snack",
    "Starter",
    "Soup",
    "Salad",
    "Side",
    "Main",
    "Shared Plate",
    "Dessert",
    "Bread",
    "Dough",
    "Sauce",
    "Condiment",
    "Drink",
    "Preserve",
    "Pantry Staple",
    "Component",
    "Confectionery",
    "Street Food",
]

PRIMARY_CUISINES = [
    "Italian",
    "French",
    "Spanish",
    "Catalan",
    "Portuguese",
    "Greek",
    "Turkish",
    "British",
    "Irish",
    "Scottish",
    "Nordic",
    "Swedish",
    "Norwegian",
    "Danish",
    "Finnish",
    "German",
    "Austrian",
    "Swiss",
    "Dutch",
    "Belgian",
    "Eastern European",
    "Polish",
    "Hungarian",
    "Czech",
    "Romanian",
    "Russian",
    "Georgian",
    "Armenian",
    "Ukrainian",
    "Levantine",
    "Lebanese",
    "Syrian",
    "Palestinian",
    "Israeli",
    "Egyptian",
    "Moroccan",
    "Tunisian",
    "Algerian",
    "Libyan",
    "Persian",
    "Iraqi",
    "Yemeni",
    "Ethiopian",
    "Eritrean",
    "West African",
    "Nigerian",
    "Ghanaian",
    "Senegalese",
    "East African",
    "Kenyan",
    "South African",
    "Zimbabwean",
    "Indian",
    "North Indian",
    "South Indian",
    "Pakistani",
    "Bangladeshi",
    "Sri Lankan",
    "Nepali",
    "Thai",
    "Vietnamese",
    "Cambodian",
    "Laotian",
    "Filipino",
    "Indonesian",
    "Malaysian",
    "Singaporean",
    "Burmese",
    "Chinese",
    "Cantonese",
    "Sichuan",
    "Shanghainese",
    "Taiwanese",
    "Japanese",
    "Korean",
    "Mongolian",
    "Uzbek",
    "Kazakh",
    "Azerbaijani",
    "Caucasian",
    "Mexican",
    "Tex-Mex",
    "Oaxacan",
    "Central American",
    "Guatemalan",
    "Peruvian",
    "Colombian",
    "Venezuelan",
    "Brazilian",
    "Argentinian",
    "Chilean",
    "American",
    "American Southern",
    "American Midwest",
    "Cajun / Creole",
    "Caribbean",
    "Jamaican",
    "Cuban",
    "Fusion",
    "Global / Mixed",
]

TECHNIQUE_FAMILIES = [
    "Raw",
    "Assemble",
    "Marinate",
    "Cure",
    "Ferment",
    "Pickle",
    "Smoke",
    "Confit",
    "Poach",
    "Steam",
    "Boil",
    "Simmer",
    "Braise",
    "Stew",
    "Slow Cook",
    "Pressure Cook",
    "Sear",
    "Fry",
    "Stir-Fry",
    "Deep Fry",
    "Roast",
    "Bake",
    "Grill",
    "Emulsify",
    "Blend",
    "Dehydrate",
    "Multi-Stage",
]

COMPLEXITIES = ["Basic", "Intermediate", "Advanced", "Project"]
TIME_CLASSES = ["Under 15 min", "15–30 min", "30–60 min", "1–2 hr", "2–4 hr", "Half Day+", "Multi-Day"]
SERVICE_FORMATS = [
    "Single Plate",
    "Family Style",
    "Buffet / Shared",
    "Meal Prep",
    "Party Food",
    "Lunchbox",
    "Sauce / Add-On",
    "Side Component",
    "Base Recipe",
    "Kitchen Use",
]
SEASONS = ["Spring", "Summer", "Autumn", "Winter", "All Year"]

VALUE_ALIASES = {
    "dish_role": {
        "main": "Main",
        "main course": "Main",
        "main_course": "Main",
        "main-course": "Main",
        "starter course": "Starter",
        "side dish": "Side",
        "shared": "Shared Plate",
        "shared_plate": "Shared Plate",
        "sauce / condiment": "Sauce",
    },
    "technique_family": {
        "raw / no-cook": "Raw",
        "no cook": "Assemble",
        "no-cook": "Assemble",
        "sauce_emulsion": "Emulsify",
        "emulsion": "Emulsify",
        "pan fry": "Fry",
        "stir fry": "Stir-Fry",
        "deep-fry": "Deep Fry",
        "pressure-cook": "Pressure Cook",
        "slow-cook": "Slow Cook",
    },
    "service_format": {
        "hot plated": "Single Plate",
        "hot_plated": "Single Plate",
        "single_plate": "Single Plate",
        "family_style": "Family Style",
        "meal_prep": "Meal Prep",
    },
    "season": {
        "all_year": "All Year",
        "year-round": "All Year",
        "year round": "All Year",
    },
}

VOLUME_TO_ML = {
    "krm": 1.0,
    "kryddmått": 1.0,
    "tsp": 4.92892,
    "teaspoon": 4.92892,
    "teaspoons": 4.92892,
    "tsk": 4.92892,
    "tbsp": 14.7868,
    "tablespoon": 14.7868,
    "tablespoons": 14.7868,
    "msk": 14.7868,
    "fl oz": 29.5735,
    "fluid ounce": 29.5735,
    "fluid ounces": 29.5735,
    "cup": 236.588,
    "cups": 236.588,
    "pint": 473.176,
    "pints": 473.176,
    "quart": 946.353,
    "quarts": 946.353,
}

WEIGHT_TO_G = {
    "oz": 28.3495,
    "ounce": 28.3495,
    "ounces": 28.3495,
    "lb": 453.592,
    "lbs": 453.592,
    "pound": 453.592,
    "pounds": 453.592,
}

METRIC_UNIT_MAP = {
    "gram": "g",
    "grams": "g",
    "g": "g",
    "kilogram": "kg",
    "kilograms": "kg",
    "kg": "kg",
    "milliliter": "ml",
    "milliliters": "ml",
    "ml": "ml",
    "deciliter": "dl",
    "deciliters": "dl",
    "dl": "dl",
    "decilitre": "dl",
    "decilitres": "dl",
    "liter": "l",
    "liters": "l",
    "l": "l",
    "krm": "ml",
    "kryddmått": "ml",
}

KNOWN_UNIT_TOKENS = {
    "g",
    "gram",
    "grams",
    "kg",
    "mg",
    "ml",
    "cl",
    "dl",
    "l",
    "tsp",
    "tbsp",
    "msk",
    "tsk",
    "cup",
    "cups",
    "oz",
    "lb",
    "piece",
    "pinch",
    "small",
    "medium",
    "large",
    "clove",
    "cloves",
}

PREPARATION_REPLACEMENTS = (
    (r"\bfin chopped\b", "finely chopped"),
    (r"\bfinely chop\b", "finely chopped"),
    (r"\bgrated coarse\b", "coarsely grated"),
    (r",\s*grated coarse\b", ", coarsely grated"),
    (r",\s*grated coarsely\b", ", coarsely grated"),
    (r"\bgrated finely\b", "finely grated"),
    (r",\s*grated finely\b", ", finely grated"),
    (r"\bground freshly\b", "freshly ground"),
)

SUSPICIOUS_ITEM_PREFIXES = (
    "from ",
    "with ",
    "for ",
    "to ",
    "optional ",
)
